### ISSUE TITLE
Add support for setting JSON Feature Object in GBContext builder

### ISSUE THREAD

**Issue by gaurav-rana** [growthbook/growthbook-sdk-java#77]
The current GBContext implementation is suboptimal for java backend integrations.
We have to create a new GBContext for each request, and because the CustomGbContextBuilder only supports StringType featureJson, we have to pass featureJson as string and it parses the JSON (converting from String to JSONType) for each and every request.
This can be avoided by letting the application maintain JSON and set JSON directly.

Flame graph with the current GBContext:

![image](https://github.com/growthbook/growthbook-sdk-java/assets/11795117/1f2fb79c-81d7-4146-9089-436c091f8560)

As we can see, around 42% of total CPU is spent inside parsing this JSON for each and every request, this overhead can be clearly avoided by letting the client set the JSON directly instead of string.

I've added the support in this PR
https://github.com/growthbook/growthbook-sdk-java/pull/76

**Comment by Bohdan-Kim** [comment]
Passing features not through `String` type but  through `JsonObject` type was suggested in PR. We can't remove old way through `String` type  because it leads to rewriting all tests, but to add also passing through `JsonObject` type is OK.
So, `JsonObject` type from `Gson` library was added to public class `GbContext` of the GrowthBook Java SDK. It can lead to forcing users of the SDK to include Gson dependency in their apps. In order not to include `Gson` in target builds if they are passing features through `String` type `compileOnly` can be used:
```
compileOnly 'com.google.code.gson:gson:2.9.1'
```

**Comment by Bohdan-Kim** [comment]
The pull request is not merged in `main` branch yet but the changes can be accessed using this:
```
	<dependency>
	    <groupId>com.github.growthbook</groupId>
	    <artifactId>growthbook-sdk-java</artifactId>
	    <version>release~0.9.7-SNAPSHOT</version>
	</dependency>
```

**Comment by vazarkevych** [comment]
Hi, @gaurav-rana. We have added the necessary changes and successfully merged your pull request.[](https://github.com/growthbook/growthbook-sdk-java/pull/76)

**Comment by gaurav-rana** [comment]
Great Thanks! 
I'm waiting for the release `0.9.7` before i upgrade the SDK in my app.

**Comment by Bohdan-Kim** [comment]
`0.9.7` version is available on [JitPack](https://jitpack.io/#growthbook/growthbook-sdk-java/0.9.7)

**Comment by gaurav-rana** [comment]
Thanks, closing this as completed.
